[package]
name = "rustedcars"
version = "0.1.0"
authors = ["Kesara Rathnayake <kesara@fq.nz>"]
license = "GPL-3.0"

[dependencies]
rand = "0.3"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["ttf"]
